spring:
  application:
    name: transaction-management-service
management:
  endpoints:
    prometheus:
        enabled: true
    web:
      exposure:
        include: health, prometheus, metrics
  metrics:
    tag:
      ${spring.application.name}
  endpoint:
    health:
      show-details: always