openapi: '3.0.1'

info:
  title: User
  version: 1.0
  description: "test"

servers:
  - url: http://localhost:8080/api
    description: Local Server
paths:
  /user:
    get:
      summary: Save User
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string