apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ldap-monitoring-app
spec:
  project: development
  source:
    repoURL: 
    targetRevision: HEAD
    path: 
  destination:
    server: https://kubernetes.default.svc
    namespace: 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false