version: "1.0"
services:
  application:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8088:8088
    network_mode: host
  prometheus:
    image: bitnami/prometheus
    network_mode: host
    ports:
      - 9090:9090
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "COPY prometheus.yaml /etc/prometheus"
    extra_hosts:
      - host.docker.internal:host-gateway
  grafana:
    image: grafana/grafana-oss:8.5.2
    user: root
    ports:
      - 3000:3000
    links:
      - prometheus:prometheus