global:
  scrap_interval: 5s
scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/theta/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8088']