apiVersion: apps/v1
kind: Deployment
metadata:
  name: txmgmt-app-deployment
spec:
  selector:
    matchLabels:
      app: txmgmt-app-new
  template:
    metadata:
      labels:
        app: txmgmt-app-new
    spec:
      containers:
      - name: txmgmt-container
        image: 100819880101/txtmgmt-latest:1.10.0
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: txmgmt-app-clusterip
#  annotations:
#    prometheus.io/scrape: "true"
#spec:
#  type: ClusterIP
#  selector:
#    app: txmgmt-app
#  ports:
#  - port: 8083
#    targetPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: txmgmt-app-nodeport
  annotations:
    prometheus.io/scrape: "true"
spec:
  type: NodePort
  selector:
    app: txmgmt-app-new
  ports:
  - port: 8080
    targetPort: 8080