apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-application-analyzer
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: 100819880101/myapp:~1.0
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: main
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/hiral-yadav/vendor-transaction-management
    targetRevision: HEAD
    path: 
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true