apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactionmanagement-deployment
  labels:
    app: transactionmanagement-deployment
  namespace: monitoring
spec:
  template:
    metadata:
      labels:
        app: transactionmanagement
    spec:
      containers:
      - name: transactionmanagement-deployment
        resources:
          limits:
            memory: "1024Mi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: transactionmanagement-service
  namespace: monitoring
  labels:
    app: transactionmanagement-clusterIP-service
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app: transactionmanagement-deployment
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: web
    protocol: TCP
    port: 8087
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: transactionmanagement-nodeport
  namespace: monitoring
  labels:
    app: transactionmanagement-nodeport
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app: transactionmanagement-clusterIP-service
  type: NodePort
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: web-app
    protocol: TCP
    port: 8080
    targetPort: 8080
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: transactionmanagementextname
#  namespace: monitoring
#  labels:
#    app: transactionmanagementextname
#spec:
#  type: ExternalName
#  externalName: transactionmanagementcip.monitoring.svc.cluster.local
#---
#apiVersion: monitoring.coreos.com/v1
#kind: ServiceMonitor
#metadata:
#  labels:
#  name: transactionmanagement-servicemonitor
#  namespace: monitoring
#spec:
#  endpoints:
#  - interval: 30s
#    port: web
#  selector:
#    matchLabels:
#      app: transactionmanagementcip
#  namespaceSelector:
#    matchNames:
#    - monitoring