apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactionmanagement-deployment
  labels:
    app: transactionmanagement-deployment
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: transactionmanagement
  template:
    metadata:
      labels:
        app: transactionmanagement
    spec:
      containers:
      - name: transactionmanagement-deployment
        image: 100819880101/myapp:1.0
        resources:
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8087
---
apiVersion: v1
kind: Service
metadata:
  name: transactionmanagementcip
  namespace: monitoring
  labels:
    app: transactionmanagementcip  
spec:
  selector:
    app: transactionmanagement-deployment
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: 8087
---
apiVersion: v1
kind: Service
metadata:
  name: transactionmanagement-nodeport
  namespace: monitoring
  labels:
    app: transactionmanagement-nodeport
spec:
  selector:
    app: transactionmanagement-deployment
  type: NodePort
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: web-nodeport
    protocol: TCP
    port: 80
    targetPort: 8087
---
apiVersion: v1
kind: Service
metadata:
  name: transactionmanagementextname
  namespace: monitoring
  labels:
    app: transactionmanagementextname 
spec:
  type: ExternalName
  externalName: transactionmanagementcip.monitoring.svc.cluster.local
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
  name: transactionmanagement-servicemonitor
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: web
  selector: 
    matchLabels:
      app: transactionmanagementcip
  namespaceSelector:
    matchNames:
    - monitoring