name: build docker image

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: java setup
        uses: actions/setup-java@v4
        with: 
          distribution: zulu
          java-version: '17'
          
      - name: build project
        run: | 
          mvn clean install
        env: 
          CI: true
