name: build docker image

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: java setup
        uses: actions/setup-java@v4
        with: 
          distribution: zulu
          java-version: '17'
          
      - name: build project
        run: | 
          mvn clean install
        env: 
          CI: true

      - name: docker build image
        uses: docker/setup-buildx-action@v3

      - name: docker login
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}
        
      
      
      
