name: build docker image

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup Maven
        uses: aahmed-se/setup-maven@v3
        with:
          maven-version: 3.6.1
        
      - name: build project
        run: | 
          mvn clean install
        env: 
          CI: true
