name: build docker image

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: development
      url: https://github.com/hiral-yadav/vendor-transaction-management
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: java setup
        uses: actions/setup-java@v4
        with: 
          distribution: zulu
          java-version: '17'
          
      - name: build project
        run: | 
          mvn clean install
        env: 
          CI: true

      - name: docker intialize
        uses: docker/setup-buildx-action@v3

      - name: docker build
        run: |
          docker build . -t 'vendor-management-service:1.0.0'
    
      - name: docker login
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}

      - name: docker push
        uses: docker/build-push-action@v5
        with: 
          push: true
          tags: ${{ secrets.docker_username }}/vendor-management-service:1.0.0
          
      
