name: vendor-transaction-mgmt-job
'on': push
jobs:
  build:
    steps:
      - 
        name: checkout
        uses: actions/checkout@v4
      - 
        name: docker-build
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug