name: vendor-transaction-mgmt-job
'on': push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        id: github-checkout 
        
      - name: docker-build
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
        id: docker-build
